# Generated by Django 4.2.3 on 2023-07-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('seat_number', 'date')},
            },
        ),
    ]
